// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX36pBKsAlD1bQxmE1LOzox8NOyBKL0t0',
    appId: '1:5766703152:web:1561e0f21254309b5b25f5',
    messagingSenderId: '5766703152',
    projectId: 'authentication-app-39b1a',
    authDomain: 'authentication-app-39b1a.firebaseapp.com',
    databaseURL: 'https://authentication-app-39b1a-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-app-39b1a.firebasestorage.app',
    measurementId: 'G-CW8KP9Q7TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5soSZMid25wENt2rmoKCWGqWBRfqmLM4',
    appId: '1:5766703152:android:52e37124d65429205b25f5',
    messagingSenderId: '5766703152',
    projectId: 'authentication-app-39b1a',
    databaseURL: 'https://authentication-app-39b1a-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-app-39b1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6NQHuoLqyxZa1m3kIRF_bTAaFEpx5CNE',
    appId: '1:5766703152:ios:ba4ad3eb96d49c4d5b25f5',
    messagingSenderId: '5766703152',
    projectId: 'authentication-app-39b1a',
    databaseURL: 'https://authentication-app-39b1a-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-app-39b1a.firebasestorage.app',
    iosBundleId: 'com.example.ggClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6NQHuoLqyxZa1m3kIRF_bTAaFEpx5CNE',
    appId: '1:5766703152:ios:ba4ad3eb96d49c4d5b25f5',
    messagingSenderId: '5766703152',
    projectId: 'authentication-app-39b1a',
    databaseURL: 'https://authentication-app-39b1a-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-app-39b1a.firebasestorage.app',
    iosBundleId: 'com.example.ggClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX36pBKsAlD1bQxmE1LOzox8NOyBKL0t0',
    appId: '1:5766703152:web:0efac3d74fd7c5415b25f5',
    messagingSenderId: '5766703152',
    projectId: 'authentication-app-39b1a',
    authDomain: 'authentication-app-39b1a.firebaseapp.com',
    databaseURL: 'https://authentication-app-39b1a-default-rtdb.firebaseio.com',
    storageBucket: 'authentication-app-39b1a.firebasestorage.app',
    measurementId: 'G-4V765FKSS5',
  );
}
